"""
webauthn_bridge.py
-------------------
The browser-side half of passkey support. Streamlit's Python code can't
call navigator.credentials.create()/get() itself -- only JavaScript
running in the browser can prompt the OS for a fingerprint, face scan,
or PIN. This file defines a small Components v2 component that:

1. Receives WebAuthn options generated by webauthn_utils.py (as JSON)
2. Converts the base64url-encoded fields into the binary ArrayBuffers
   the browser API actually requires
3. Calls navigator.credentials.create() (registration) or .get() (login)
4. Converts the browser's response back into JSON and sends it to Python

NOTE ON TESTING: everything server-side (webauthn_utils.py, db.py) has
been tested against a synthetic authenticator that produces
spec-compliant responses, proving the cryptographic verification is
correct. This file -- the part that actually talks to real biometric
hardware through a real browser -- could NOT be tested the same way,
since that requires an actual device. Test this part carefully on real
hardware before relying on it.
"""

import streamlit as st

_HTML = """
<div style="display:flex; flex-direction:column; gap:8px; align-items:flex-start;">
  <button id="wa-trigger" type="button" style="
      padding: 0.5rem 1rem;
      border-radius: 0.5rem;
      border: 1px solid var(--st-border-color, #999);
      background: var(--st-secondary-background-color, transparent);
      color: var(--st-text-color, inherit);
      font-family: var(--st-font, inherit);
      cursor: pointer;
  ">Use biometric / passkey</button>
  <div id="wa-status" style="font-size: 0.85em; opacity: 0.85;"></div>
</div>
"""

_JS = """
export default function(component) {
    const { data, setTriggerValue, parentElement } = component;

    function base64urlToBuffer(base64url) {
        const padding = "=".repeat((4 - (base64url.length % 4)) % 4);
        const base64 = (base64url + padding).replace(/-/g, "+").replace(/_/g, "/");
        const raw = atob(base64);
        const buffer = new ArrayBuffer(raw.length);
        const bytes = new Uint8Array(buffer);
        for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
        return buffer;
    }

    function bufferToBase64url(buffer) {
        const bytes = new Uint8Array(buffer);
        let str = "";
        for (let i = 0; i < bytes.byteLength; i++) str += String.fromCharCode(bytes[i]);
        return btoa(str).replace(/\\+/g, "-").replace(/\\//g, "_").replace(/=+$/, "");
    }

    const statusEl = parentElement.querySelector("#wa-status");
    const button = parentElement.querySelector("#wa-trigger");

    async function run() {
        if (!window.PublicKeyCredential) {
            statusEl.innerText = "This browser does not support passkeys.";
            setTriggerValue("result", { error: "not_supported" });
            return;
        }

        const action = data.action;
        const optionsRaw = JSON.parse(data.options_json);
        button.disabled = true;
        statusEl.innerText = "Follow your device's prompt (fingerprint, face, or PIN)...";

        try {
            if (action === "register") {
                const publicKey = {
                    ...optionsRaw,
                    challenge: base64urlToBuffer(optionsRaw.challenge),
                    user: {
                        ...optionsRaw.user,
                        id: base64urlToBuffer(optionsRaw.user.id),
                    },
                    excludeCredentials: (optionsRaw.excludeCredentials || []).map((c) => ({
                        ...c,
                        id: base64urlToBuffer(c.id),
                    })),
                };
                const credential = await navigator.credentials.create({ publicKey });
                const result = {
                    id: credential.id,
                    rawId: bufferToBase64url(credential.rawId),
                    type: credential.type,
                    response: {
                        clientDataJSON: bufferToBase64url(credential.response.clientDataJSON),
                        attestationObject: bufferToBase64url(credential.response.attestationObject),
                    },
                    clientExtensionResults: credential.getClientExtensionResults(),
                };
                statusEl.innerText = "Device registered.";
                setTriggerValue("result", { ok: true, credential: result });
            } else if (action === "authenticate") {
                const publicKey = {
                    ...optionsRaw,
                    challenge: base64urlToBuffer(optionsRaw.challenge),
                    allowCredentials: (optionsRaw.allowCredentials || []).map((c) => ({
                        ...c,
                        id: base64urlToBuffer(c.id),
                    })),
                };
                const credential = await navigator.credentials.get({ publicKey });
                const result = {
                    id: credential.id,
                    rawId: bufferToBase64url(credential.rawId),
                    type: credential.type,
                    response: {
                        clientDataJSON: bufferToBase64url(credential.response.clientDataJSON),
                        authenticatorData: bufferToBase64url(credential.response.authenticatorData),
                        signature: bufferToBase64url(credential.response.signature),
                    },
                    clientExtensionResults: credential.getClientExtensionResults(),
                };
                statusEl.innerText = "Verified.";
                setTriggerValue("result", { ok: true, credential: result });
            }
        } catch (err) {
            statusEl.innerText = "Failed: " + (err && err.message ? err.message : String(err));
            setTriggerValue("result", { error: String(err && err.message ? err.message : err) });
        } finally {
            button.disabled = false;
        }
    }

    button.onclick = run;
}
"""

_webauthn_component = st.components.v2.component(
    "webauthn_bridge",
    html=_HTML,
    js=_JS,
)


def webauthn_prompt(action: str, options_json: str, key: str, on_result=lambda: None):
    """Mounts the passkey button. action is 'register' or 'authenticate'.
    Returns the result object; result.result is None until the button is
    clicked and the browser ceremony completes (successfully or not),
    at which point it holds the JSON payload described in this module's
    JS, for exactly one script rerun."""
    return _webauthn_component(
        data={"action": action, "options_json": options_json},
        key=key,
        on_result_change=on_result,
    )